version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agendamento-notificacoes
    restart: always
    environment:
      - MYSQL_DATABASE=agendamento-notificacoes
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    volumes:
      - volume:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendamento-notificacoes-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agendamento-notificacoes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    restart: always

volumes:
  volume:
